elasticsearch:
  version: "8.6.1"
  search:
    hosts:
      - http://localhost:9200

spring:
  main:
    web-application-type: none
    banner-mode: off
  include:
    - elasticsearch
  ai:
    mcp:
      server:
        stdio: true
        name: elasticsearch-mcp-server
        version: 0.0.1
        type: ASYNC
        resource-change-notification: false
        prompt-change-notification: false
        tool-change-notification: false

logging:
  config: classpath:logback-prod.xml